# Generated by Django 4.1.1 on 2022-09-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIServer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='bank',
            new_name='bank_id',
        ),
    ]
