# Generated by Django 4.1.1 on 2022-09-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIServer', '0005_rename_bank_id_branches_bankid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='bankId',
            new_name='bank',
        ),
    ]
